name: infinite_recharge_scouting
description: Team 1257 Infinite Recharge Scouting App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_for_web: ^1.0.0
  flutter_for_web_ui: ^1.0.0
  http: ^0.12.0+4

dev_dependencies:
  build_runner: any
  build_web_compilers: any

flutter:
  uses-material-design: true